In [1]:
import sys  
sys.path.insert(0, '../')

In [2]:
import os
import numpy as np
import GPyOpt
from feature_extraction.loan_struct_reader import LoanStructReader
from feature_extraction.loan_options_maker import LoanOptionsMaker
from feature_extraction.loan_concatenator import LoanConcatenator
from feature_extraction.loan_markuper import LoanMarkuper
from feature_extraction.hist_market_worker import HistMarketDataWorker

from scipy.stats.contingency import margins
import matplotlib.pyplot as plt
import scipy.stats as ss
import math

warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy


In [3]:
plt.rcParams["axes.labelsize"] = 16. 
plt.rcParams["xtick.labelsize"] = 14. 
plt.rcParams["ytick.labelsize"] = 14. 
plt.rcParams["legend.fontsize"] = 12. 
plt.rcParams["figure.figsize"] = [15., 6.]

In [4]:
PROJECT_PATH = os.path.dirname(os.getcwd())
DOMAIN = [{'name': 'var_1', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_2', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_3', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_4', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_5', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_6', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_7', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_8', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_9', 'type': 'continuous', 'domain': (0, 1)},
          {'name': 'var_10', 'type': 'continuous', 'domain': (0, 1)}]

DOMAIN_1 = {'name': 'var_1', 'type': 'continuous', 'domain':(0, 1), 'dimensionality':10}

In [5]:
def f(X, json_example_path=os.path.join(PROJECT_PATH, r"json_real", r"sample_1.json")):
    "It should take 2-dimensional numpy arrays as input and return 2-dimensional outputs (one evaluation per row)"
    Y = []
    for x in X:
        struct, original_options = LoanStructReader().Read(json_example_path, returnOptions=True)
        options = LoanOptionsMaker().Make(original_options, ir_curve=x)

        loan = LoanConcatenator(struct, options, {}).Parse()
        Y.append([LoanMarkuper().MarkupLoan(loan)])
    return np.array(Y)

-----------
### Test on empirical observations

In [6]:
mu = np.array([0.999791,  0.99853703,  0.99374632,  0.98132504,  0.96271221,
        0.92621573,  0.85829915,  0.67985138,  0.4574298,  0.45154276])
cov = np.cov(np.random.rand(10,10))

In [7]:
hmdw = HistMarketDataWorker().load()

In [8]:
normal_dist_1 = ss.multivariate_normal(mean=hmdw.get_func().mean, cov=hmdw.get_func().cov, allow_singular=True)
normal_dist_2 = ss.multivariate_normal(mean=hmdw.get_func().mean, cov=cov, allow_singular=True)
rho_foo_1 = lambda X: np.array([[normal_dist_1.pdf(x)] for x in X])

In [9]:
hmdw.get_func().cov

array([[  1.68364856e-11,   1.17855399e-10,   4.84730408e-10,
          1.43678159e-09,   2.75599180e-09,   5.31215103e-09,
          1.00413010e-08,   2.14812457e-08,   2.90042984e-08,
          2.92104868e-08],
       [  1.17855399e-10,   8.24987793e-10,   3.39311286e-09,
          1.00574711e-08,   1.92919426e-08,   3.71850572e-08,
          7.02891071e-08,   1.50368720e-07,   2.03030089e-07,
          2.04473407e-07],
       [  4.84730408e-10,   3.39311286e-09,   1.46573849e-08,
          4.23008916e-08,   7.81069061e-08,   1.42614838e-07,
          2.57516001e-07,   5.75501836e-07,   8.67940396e-07,
          8.75678783e-07],
       [  1.43678159e-09,   1.00574711e-08,   4.23008916e-08,
          1.41398817e-07,   3.08534936e-07,   6.61392309e-07,
          1.24699012e-06,   2.08307409e-06,   1.92202021e-06,
          1.91585845e-06],
       [  2.75599180e-09,   1.92919426e-08,   7.81069061e-08,
          3.08534936e-07,   8.09740663e-07,   2.00397555e-06,
          4.02922430e-06

---------

In [10]:
X_init = np.array(np.ones(HistMarketDataWorker().load().get_sample().shape).reshape(1, -1))
print(X_init.shape)
Y_init = f(X_init)
print(Y_init)

bo = GPyOpt.methods.BayesianOptimization(f=f, domain=DOMAIN,
                                        initial_design_numdata = 5,
                                        X=X_init, Y=Y_init,
                                        acquisition_type='LCB',
                                        exact_feval = True,
                                        normalize_Y = False,
                                        optimize_restarts = 10,
                                        acquisition_weight = 2,
                                        de_duplication = True)
                                        #rho_func = rho_foo_1, #hmdw.rho_normal,
                                        #exploration_weight=1000,
                                        #with_noise=False)

X_test = []
for i in range(20):
    X_test.append(hmdw.get_sample())
X_test = np.array(X_test)

bo.run_optimization(50)#, test_X = X_test)
print('evaluations_list: ', bo.get_evaluations())

print('test_sample_values:')
predict = bo.model.predict(X_test)
print('\mu_values: ', predict[0])
print('\sigma_values: ', predict[1])
print('MAE: ', np.mean(predict[1] / predict[0]))
#print('MAE_list: ', bo.error_list)

(1, 10)
[[ 99999999.99999975]]
evaluations_list:  (array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000

In [11]:
X_test[0]

array([ 0.99979   ,  0.99853001,  0.99374179,  0.9811724 ,  0.96210082,
        0.92407917,  0.85574636,  0.67502077,  0.45838138,  0.45276679])

In [12]:
bo.model.predict(X_test[0])

(array([[ 0.]]), array([[ 315996.78703423]]))

-----------
### Check statistics from X_test

In [13]:
X_test = []
for i in range(20000):
    X_test.append(hmdw.get_sample())
X_test = np.array(X_test)

In [14]:
X_test

array([[ 0.99979216,  0.99854513,  0.99375912, ...,  0.67933234,
         0.44337376,  0.43703739],
       [ 0.99979332,  0.99855326,  0.99379877, ...,  0.68846262,
         0.47221814,  0.46659297],
       [ 0.99978685,  0.99850798,  0.99359321, ...,  0.67568777,
         0.45453427,  0.44840936],
       ..., 
       [ 0.99979306,  0.99855145,  0.99381596, ...,  0.67571569,
         0.45371672,  0.4476139 ],
       [ 0.9997916 ,  0.99854123,  0.99373869, ...,  0.6834177 ,
         0.45481212,  0.44884008],
       [ 0.99978861,  0.99852025,  0.99366064, ...,  0.68843989,
         0.45161151,  0.44531562]])

In [15]:
mean_values = np.mean(np.transpose(X_test), 1)
mean_values

array([ 0.999791  ,  0.99853703,  0.99374632,  0.98132504,  0.96271221,
        0.92621573,  0.85829915,  0.67985138,  0.4574298 ,  0.45154276])

In [16]:
np.std(np.transpose(X_test), 1)

array([  4.08725409e-06,   2.86107792e-05,   1.20669247e-04,
         3.75176684e-04,   9.02358560e-04,   2.35545598e-03,
         5.14899681e-03,   8.13050804e-03,   9.45530094e-03,
         9.63005707e-03])

------------

In [17]:
a1 = bo.error_list[1:]
b1 = bo.test_error_list[1:]

AttributeError: 'BayesianOptimization' object has no attribute 'error_list'

In [ ]:
plt.plot(a1, label = 'train_MAE')
plt.plot(b1, label = 'model_MAE')
#plt.plot([np.mean(predict[1] / predict[0]) for _ in range(len(bo.error_list)-1)], color = 'red', label = 'test_MAE')
plt.legend()
plt.show()

In [ ]:
plt.plot(np.diff(bo.test_error_list[1:])[20:])
print('maximum_diff: ', max(np.diff(bo.test_error_list[1:])[20:]))
plt.show()

In [ ]:
np.std(np.transpose(X_test)[0])

In [ ]:
rho = lambda x: ss.norm.pdf(x, loc = np.mean(np.transpose(X_test)[0]), scale = np.sqrt(hmdw.get_func().cov[0][0]))

x = np.linspace(0.9997, 0.9999, 10000)
plt.plot(x, rho(x), 'k-', lw=2, label='frozen pdf')
plt.hist(np.transpose(X_test)[0], bins = 30, normed = True)
plt.grid()
plt.title('first argument distribution')
plt.show()

In [ ]:
rho = lambda x: ss.norm.pdf(x, loc = np.mean(np.transpose(X_test)[1]), scale = np.sqrt(hmdw.get_func().cov[1][1]))

x = np.linspace(0.9984, 0.9988, 10000)
plt.plot(x, rho(x), 'k-', lw=2, label='frozen pdf')
plt.hist(np.transpose(X_test)[1], bins = 30, normed = True)
plt.grid()
plt.title('first argument distribution')
plt.show()

In [ ]:
rho = lambda x: ss.norm.pdf(x, loc = np.mean(np.transpose(X_test)[-1]), scale = np.sqrt(hmdw.get_func().cov[-1][-1]))

x = np.linspace(0.4, 0.5, 10000)
plt.plot(x, rho(x), 'k-', lw=2, label='frozen pdf')
plt.hist(np.transpose(X_test)[-1], bins = 30, normed = True)
plt.grid()
plt.title('last argument distribution')
plt.show()

In [ ]:
hmdw.get_func().cov[0][0]*1e7

### Check data on test points
---------------

In [ ]:
vals = bo.get_evaluations()
X = vals[0]
y = [k[0] for k in vals[1]]

In [ ]:
plt.hist(X.T[0], bins = 40, label = "First_argument")
plt.axvline(mean_values[0], color = 'red', label = 'mean_test_value')
plt.legend()
plt.show()

In [ ]:
plt.hist(X.T[1], bins = 40, label = "Second_argument")
plt.axvline(mean_values[1], color = 'red', label = 'mean_test_value')
plt.legend()
plt.show()

In [ ]:
plt.hist(X.T[2], bins = 40, label = "Third_argument")
plt.axvline(mean_values[2], color = 'red', label = 'mean_test_value')
plt.legend()
plt.show()

In [ ]:
plt.hist(X.T[3], bins = 40, label = "Fourth_argument")
plt.axvline(mean_values[3], color = 'red', label = 'mean_test_value')
plt.legend()
plt.show()

In [ ]:
plt.hist(X.T[-1], bins = 40, label = "Last_argument")
plt.axvline(mean_values[-1], color = 'red', label = 'mean_test_value')
plt.legend()
plt.show()

----------
### Lets look at the histogram of the avaliable values relative to the theoretical distribution for the model covariance matrix

In [ ]:
plt.plot(np.arange(0,1, 0.0001), np.array(bo.sigma_arr)[2])
plt.title('sigma_array')
plt.show()

--------------
#### Get sigma arrays

In [ ]:
for k in range(10):
    plt.plot(np.arange(0,1, 0.0001), np.array(bo.sigma_arr)[k], label = 'sigma_'+str(k))
plt.title('sigma_arrays')
plt.legend()
plt.show()

-------------

In [ ]:
get_prob_arr = lambda k: ss.norm.pdf(x = np.linspace(0,1,10000), loc = hmdw.get_func().mean[k], scale = np.sqrt(hmdw.get_func().cov[k][k]))
marginal_dist = margins(np.array([get_prob_arr(i) for i in range(10)]))[1]

In [ ]:
rho_arr = ss.norm.pdf(x = np.arange(0,1,0.0001), loc = hmdw.get_func().mean[-1], scale = np.sqrt(hmdw.get_func().cov[-1][-1]))
arr = np.array([np.arange(0,1,0.0001) for _ in range(10)])
mass = rho_foo_1(arr.T)

In [ ]:
for k in range(np.array(bo.sigma_arr).shape[0]):
    plt.plot(np.arange(0,1,0.0001), np.array(bo.sigma_arr)[k].reshape(-1)*rho_arr)
    plt.axvline(X.T[0][1:][k])
    plt.show()

In [ ]:
bo.sigma_arr

In [ ]:
for k in range(np.array(bo.sigma_arr).shape[0]):
    plt.plot(np.arange(0,1,0.0001), np.array(bo.sigma_arr)[k].reshape(-1)*rho_arr)
    plt.axvline(X.T[0][1:][k], color = 'green', alpha = 0.2, linewidth = 0.5)
plt.show()

In [ ]:
plt.plot(np.arange(0,1,0.0001), rho_arr)
plt.hist(X.T[0], bins = 40, label = "First_argument", normed = True)
plt.show()

In [ ]:
plt.plot(np.linspace(0,1,10000), marginal_dist[0])
plt.title('marginal distribution')
plt.show()

In [ ]:
# get covariance matrix (diagonal)
np.diag(hmdw.get_func().cov)

In [ ]:
# get mean values
hmdw.get_func().mean

In [ ]:
plt.plot(np.linspace(0.,1.,10000), np.array([get_prob_arr(i) for i in range(10)])[0])
plt.show()

In [ ]:
#plt.plot(np.linspace(0,1,10000), marginal_dist[0])
plt.hist(np.sum(X.T, 0)/max(np.sum(X.T, 0)), normed = True, bins = 20)
plt.title('Is it legal?')
plt.show()

In [ ]:
np.array([np.arange(0,1,0.0001) for _ in range(10)]).T